#include <vector>
#include <list>
#include <map>
#include <set>
#include <queue>
#include <deque>
#include <stack>
#include <bitset>
#include <algorithm>
#include <functional>
#include <numeric>
#include <utility>
#include <sstream>
#include <iostream>
#include <iomanip>
#include <cstdio>
#include <cmath>
#include <cstdlib>
#include <ctime>
#include <cstring>
#define all(v) (v).begin(),(v).end()
#define rall(v) (v).rbegin(),(v).rend()
#define sz size()
#define fill(x,i) memset(x,i,sizeof(x))
#define cpresent(V,e) (find(all(V),(e))!=(V).end())
#define foreach(c,it) for(__typeof((c).begin()) it=(c).begin();it!=(c).end();it++)
#define f(i,j,k) for(int i=j;j<k;i++)
using namespace std;
long long toi(string s){istringstream is(s);long long x;is>>x;return x;}
string tos(long long t){stringstream st; st<<t;return st.str();}
long long gcd(long long a, long long b){return __gcd(a,b);}
long long lcm(long long a,long long b){return a*(b/gcd(a,b));}
bool Vowel(char c){
	c=tolower(c);
	if(c=='a' || c=='e' || c=='i' || c=='o' || c=='u')
		return 1;
	return 0;
}

class CompanyName {
public:string shortestProposal(vector <string> proposals) {	
		string dev="";
		int val=1<<30;
		for(int i=0;i<proposals.sz;i++){
			string str=proposals[i];
			int a=0;
			int b=0;
			for(int j=0;j<str.sz;j++){
				if(!Vowel(str[j]))continue;
				bool ok=0;
				int k=j;
				while(k<str.sz && Vowel(str[k])){
					k++;
					ok=1;
				}
				a+=ok;
				j=k-1;
			}
			for(int j=0;j<str.sz;j++){
				if(Vowel(str[j]))continue;
				int c=0;
				int k=j;
				while(k<str.sz && !Vowel(str[k]))k++,c++;
				if(c>0)
					b+=((2*c) -1);
				j=k-1;
			}
			if(a+b<val){
				val=a+b;
				dev=str;
			}
			
		}
		return dev;		
	}
	//Powered by [Ziklon]
};
// BEGIN KAWIGIEDIT TESTING
// Generated by KawigiEdit 2.1.4 (beta) modified by pivanof
bool KawigiEdit_RunTest(int testNum, vector <string> p0, bool hasAnswer, string p1) {
	cout << "Test " << testNum << ": [" << "{";
	for (int i = 0; int(p0.size()) > i; ++i) {
		if (i > 0) {
			cout << ",";
		}
		cout << "\"" << p0[i] << "\"";
	}
	cout << "}";
	cout << "]" << endl;
	CompanyName *obj;
	string answer;
	obj = new CompanyName();
	clock_t startTime = clock();
	answer = obj->shortestProposal(p0);
	clock_t endTime = clock();
	delete obj;
	bool res;
	res = true;
	cout << "Time: " << double(endTime - startTime) / CLOCKS_PER_SEC << " seconds" << endl;
	if (hasAnswer) {
		cout << "Desired answer:" << endl;
		cout << "\t" << "\"" << p1 << "\"" << endl;
	}
	cout << "Your answer:" << endl;
	cout << "\t" << "\"" << answer << "\"" << endl;
	if (hasAnswer) {
		res = answer == p1;
	}
	if (!res) {
		cout << "DOESN'T MATCH!!!!" << endl;
	} else if (double(endTime - startTime) / CLOCKS_PER_SEC >= 2) {
		cout << "FAIL the timeout" << endl;
		res = false;
	} else if (hasAnswer) {
		cout << "Match :-)" << endl;
	} else {
		cout << "OK, but is it right?" << endl;
	}
	cout << "" << endl;
	return res;
}
int main() {
	bool all_right;
	all_right = true;
	
	vector <string> p0;
	string p1;
	
	{
	// ----- test 0 -----
	string t0[] = {"Top","Coder","SRM"};
			p0.assign(t0, t0 + sizeof(t0) / sizeof(t0[0]));
	p1 = "Top";
	all_right = KawigiEdit_RunTest(0, p0, true, p1) && all_right;
	// ------------------
	}
	
	{
	// ----- test 1 -----
	string t0[] = {"SRM","TCO","TCCC"};
			p0.assign(t0, t0 + sizeof(t0) / sizeof(t0[0]));
	p1 = "TCO";
	all_right = KawigiEdit_RunTest(1, p0, true, p1) && all_right;
	// ------------------
	}
	
	{
	// ----- test 2 -----
	string t0[] = {"java","CPP","CSharp","VBasic"};
			p0.assign(t0, t0 + sizeof(t0) / sizeof(t0[0]));
	p1 = "java";
	all_right = KawigiEdit_RunTest(2, p0, true, p1) && all_right;
	// ------------------
	}
	
	{
	// ----- test 3 -----
	string t0[] = {"aaa","AAa","aaA","AAA","AaA","Aaa"};
			p0.assign(t0, t0 + sizeof(t0) / sizeof(t0[0]));
	p1 = "aaa";
	all_right = KawigiEdit_RunTest(3, p0, true, p1) && all_right;
	// ------------------
	}
	
	{
	// ----- test 4 -----
	string t0[] = {"bIwuZFsHVQUWIABhgXYiyBmUgwSFvUfJKcGrKUb","CbjspPBtuDwlyxNMaJBIEzVDPipR","wGiqORBPEaKOYVwtiCmKHLkBS","aBpRqKPBtxYNuGMhtXmgWxT","sALonbrAMgOESizcTNhgBeAT","PpnecUCIPdyyeOvZwVHygGgjthT","jsiAzTEiBiXqgeSGd","fxUtmmfbpQoYMPenNaTtKKoCYaIhwHBJePAFtvhVPDQHiLjDcr","jIIOwgKw"};
			p0.assign(t0, t0 + sizeof(t0) / sizeof(t0[0]));
	p1 = "jIIOwgKw";
	all_right = KawigiEdit_RunTest(4, p0, true, p1) && all_right;
	// ------------------
	}
	
	if (all_right) {
		cout << "You're a stud (at least on the example cases)!" << endl;
	} else {
		cout << "Some of the test cases had errors." << endl;
	}
	return 0;
}
// END KAWIGIEDIT TESTING
//Powered by KawigiEdit 2.1.4 (beta) modified by pivanof!
